name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment:
      name: pypi
      url: https://pypi.org/project/hpvsim/

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build backend
        run: python -m pip install build

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
